# Generated by Django 5.2.15 on 2026-06-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(help_text='Short description for cards and SEO.')),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('approach', models.TextField(blank=True, help_text='Optional step-by-step approach or architecture notes.')),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies, e.g. Python, Odoo, PostgreSQL', max_length=500)),
                ('results', models.TextField(help_text='Outcomes and measurable impact.')),
                ('metric', models.CharField(blank=True, help_text='One-line outcome metric shown on cards, e.g. 40% less manual work', max_length=120)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
